# Update settings for Geyser and Floodgate
# geyser: default = true # set to true to enable Geyser updates, false to disable
# floodgate: default = true # set to true to enable Floodgate updates, false to disable
updates:
  geyser: true # Set to true to enable Geyser updates, false to disable
  floodgate: true # Set to true to enable Floodgate updates, false to disable