name: AutoUpdateGeyser
main: spigot.AutoUpdateGeyser
version: '1.0'
description: Plugin to automate updating of both Geyser and Floodgate
author: 'NewAmazingPVP'
softdepend:
  - Geyser-spigot
  - Floodgate
