name: AutoUpdateGeyser
main: spigot.AutoUpdateGeyser
version: '1.0'
description: Plugin to automate updating of both Geyser and Floodgate
author: 'NewAmazingPVP'
api-version: 1.13
folia-supported: true
softdepend:
  - Geyser-Spigot
  - floodgate