# Update settings for Geyser and Floodgate
# geyser: default = true # set to true to enable Geyser updates, false to disable\n"
# floodgate: default = true # set to true to enable Floodgate updates, false to disable\n"
# interval: default = 60 # update interval in minutes"
updates:
  geyser: true # set to true to enable Geyser updates, false to disable
  floodgate: true # set to true to enable Floodgate updates, false to disable
  interval: 60 # update interval in minutes
