# Update settings for Geyser and Floodgate
# geyser: default = true # set to true to enable Geyser updates, false to disable"
# floodgate: default = true # set to true to enable Floodgate updates, false to disable"
# interval: default = 60 # update interval in minutes"
# bootTime: default = 5 # Number of seconds the plugin should wait after the server is fully done loading to start its updating process. If set too low could cause errors
updates:
  geyser: true # Set to true to enable Geyser updates, false to disable
  floodgate: true # Set to true to enable Floodgate updates, false to disable
  interval: 60 # Update interval in minutes
  bootTime: 5 # Number of seconds the plugin should wait after the server is fully done loading to start its updating process. If set too low could cause errors

